apiVersion: v1
kind: ServiceAccount
metadata:
  name: aidemo-worker
  namespace: {{ .Values.namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.workloadIdentity.tenantId | quote }}
  labels:
    azure.workload.identity/use: "true"
